# Generated by Django 4.1.7 on 2023-02-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='customer_email',
            field=models.CharField(max_length=100),
        ),
    ]
